format_version: 10
pipelines:
  terraform-create:
    group: expense
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2ae7d73:
        git: https://github.com/devps23/expense-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
       vaultVar: "AES:SUjTbDfiAUTVz96BzdU0Mw==:c3DhvBk5xFFfw+d0TaZI5lvM8qD+Cb/jvLirOwgeNqM="
    stages:
    - DEV:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          test-job:
            timeout: 0
            tasks:
            - exec: { command: terraform, arguments: ["init","-backend-config=env-dev/state.tfvars"], run_if: passed }
            - exec: { command: terraform, arguments: ["apply","-var-file=env-dev/main.tfvars","-auto-approve"], run_if: passed }


